#!/bin/bash

export exported='exported value'
typeset -a array=('array value 1' 'array value 2' 'array value 3')
typeset -A hash=([key1]='value1' [key2]='value2' [key3]='value3')
${DEBUG:+eval $(debugtrace -p main --var fixed=fixec --var exported --var "$(declare -p array)" --var "$(declare -p hash)" -o $- -- "$@")}
