#!/bin/bash

readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }

case ",${TRACE:-}," in *,enabled,*) [ -z "$BATS_TEST_NAME" ] || BASH_XTRACEFD=3; set -x;; esac

sleep 0.1
"${scriptDir}/subordinate.sh" foo
echo EOF
