#!/bin/bash

readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }

${DEBUG:+debuglog This is the main script.}
${DEBUG:+eval $(debugtrace -p main -o $- -- "$@")}

sleep 0.1
trap 'echo EOF' EXIT
"${scriptDir}/subordinate.sh" foo bar "$@"
${DEBUG:+eval $(debugtrace -p EOF --description 'end of script' -o $-)}
