#!/bin/bash

readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }

eval "$(${DEBUG:+debugeval --} "${DEBUG:-echo}" . "$scriptDir/scriptlet.sh" lulli)" && foo
#eval "$(${DEBUG:+debugeval --command } "${DEBUG:-echo}" ". ${scriptDir@Q}/scriptlet.sh lulli")"
